name: pre_order_flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  firebase_analytics: ^8.0.1
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  provider: ^5.0.0
  google_maps_flutter: ^2.0.3
  location: ^4.0.0
  http: ^0.13.1
  fluttertoast: ^8.0.3
  uuid: ^3.0.3
  badges: ^1.2.0
  intl: ^0.17.0
  google_sign_in: ^5.0.1
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.0.5
  firebase_crashlytics: ^2.0.1
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/showroom_logo.png
    - assets/images/crowd_state_graph.png
    - assets/images/showroom_logo_bk.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon-no-alpha.png"
