# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "ad-hoc")
    upload_to_testflight
  end

  desc "Push a new beta build to Firebase App Distribution"
  lane :distribute do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "ad-hoc")
    firebase_app_distribution(
      app: "1:35020235923:ios:7108d4b69d18047c07d966",
      groups: "test",
      release_notes: "Test Distribution(iOS)",
      service_credentials_file: "/Users/sugurutakahashi/credentials/pre-order-app-2021-firebase-app-distribution.json"
    )
  end

end
